# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  
stages:
- stage: Build
  jobs:
  - job:
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
- stage: Deploy
  jobs:
  - deployment: DeployTest
    displayName: deploy Test App
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: "1"       
    cancelTimeoutInMinutes: "1" 
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'
- stage: Deploy
  jobs:
  - deployment: DeployTest_One
    displayName: deploy Test App_One
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: "1"       
    cancelTimeoutInMinutes: "1" 
    environment: 'Stage'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'
